import pandas as pd
import plotly.express as px
import streamlit as st

from research_analytics import (
    REQUIRED_CONVERSATION_COLUMNS,
    REQUIRED_SURVEY_COLUMNS,
    add_composite_scores,
    calculate_experience_summary,
    calculate_group_summary,
    calculate_intent_summary,
    calculate_risk_summary,
    validate_columns,
)

from research_report import (
    generate_statistical_report,
)

from research_statistics import (
    calculate_cronbach_alpha,
    calculate_group_confidence_intervals,
    classify_cronbach_alpha,
    run_one_way_anova,
    run_tukey_hsd,
)

from sample_data_generator import (
    generate_conversation_data,
    generate_survey_data,
)


st.title("Forex AI Disclosure Research Dashboard")

with st.expander(
    "Research methodology and interpretation guidance"
):
    st.markdown(
        """
        The dashboard analyses experimental disclosure conditions
        using descriptive statistics, scale reliability, confidence
        intervals, one-way ANOVA, eta-squared and Tukey HSD.

        Statistical significance should be interpreted together with
        effect size, uncertainty, study design and sample quality.

        Synthetic demonstration results are not empirical findings.
        """
    )

st.caption(
    "Analyse trust, credibility, risk awareness and perceived "
    "AI identity across experimental disclosure conditions."
)

st.warning(
    "Synthetic datasets are provided only to test the analytical "
    "workflow. They must not be presented as real participant results."
)


# -------------------------------------------------------------------
# Sidebar
# -------------------------------------------------------------------

with st.sidebar:
    st.header("Data Source")

    data_mode = st.radio(
        "Choose data source",
        options=[
            "Generate synthetic data",
            "Upload CSV files",
        ],
    )

    st.divider()

    if data_mode == "Generate synthetic data":
        participant_count = st.slider(
            "Synthetic participants",
            min_value=30,
            max_value=600,
            value=120,
            step=30,
        )

        random_seed = st.number_input(
            "Random seed",
            min_value=0,
            max_value=999999,
            value=42,
            step=1,
        )

        st.caption(
            "Changing the seed creates a different synthetic dataset."
        )

    else:
        st.caption(
            "Upload the survey and conversation CSV files "
            "generated by the participant application."
        )


# -------------------------------------------------------------------
# Load data
# -------------------------------------------------------------------

survey_data = pd.DataFrame()
conversation_data = pd.DataFrame()


if data_mode == "Generate synthetic data":
    try:
        survey_data = generate_survey_data(
            participant_count=participant_count,
            random_seed=int(random_seed),
        )

        conversation_data = generate_conversation_data(
            survey_data=survey_data,
            random_seed=int(random_seed),
        )

    except Exception as error:
        st.error(
            "Unable to generate synthetic data: "
            f"{error}"
        )
        st.stop()


else:
    st.subheader("Upload Research Data")

    upload_column_1, upload_column_2 = st.columns(2)

    with upload_column_1:
        uploaded_survey_file = st.file_uploader(
            "Upload survey CSV",
            type=["csv"],
            key="survey_upload",
        )

    with upload_column_2:
        uploaded_conversation_file = st.file_uploader(
            "Upload conversation CSV",
            type=["csv"],
            key="conversation_upload",
        )

    if uploaded_survey_file is not None:
        try:
            survey_data = pd.read_csv(
                uploaded_survey_file
            )

        except Exception as error:
            st.error(
                "Unable to read the survey file: "
                f"{error}"
            )

    if uploaded_conversation_file is not None:
        try:
            conversation_data = pd.read_csv(
                uploaded_conversation_file
            )

        except Exception as error:
            st.error(
                "Unable to read the conversation file: "
                f"{error}"
            )


# -------------------------------------------------------------------
# Validate survey data
# -------------------------------------------------------------------

using_synthetic_data = (
    data_mode == "Generate synthetic data"
)

if survey_data.empty:
    st.info(
        "Generate synthetic data or upload a survey CSV "
        "to begin the research analysis."
    )
    st.stop()


survey_is_valid, missing_survey_columns = validate_columns(
    survey_data,
    REQUIRED_SURVEY_COLUMNS,
)


if not survey_is_valid:
    st.error(
        "The survey dataset is missing required columns: "
        + ", ".join(missing_survey_columns)
    )
    st.stop()


# -------------------------------------------------------------------
# Validate conversation data
# -------------------------------------------------------------------

if not conversation_data.empty:
    (
        conversation_is_valid,
        missing_conversation_columns,
    ) = validate_columns(
        conversation_data,
        REQUIRED_CONVERSATION_COLUMNS,
    )

    if not conversation_is_valid:
        st.error(
            "The conversation dataset is missing required columns: "
            + ", ".join(missing_conversation_columns)
        )
        st.stop()


# -------------------------------------------------------------------
# Prepare analytical data
# -------------------------------------------------------------------

try:
    enriched_survey_data = add_composite_scores(
        survey_data
    )

    group_summary = calculate_group_summary(
        enriched_survey_data
    )

except Exception as error:
    st.error(
        "Unable to calculate research metrics: "
        f"{error}"
    )
    st.stop()


participant_total = enriched_survey_data[
    "participant_id"
].nunique()

condition_total = enriched_survey_data[
    "experiment_condition"
].nunique()

conversation_turn_total = (
    len(conversation_data)
    if not conversation_data.empty
    else 0
)

mean_trust = enriched_survey_data[
    "trust_score"
].mean()

mean_risk_awareness = enriched_survey_data[
    "risk_awareness_score"
].mean()


# -------------------------------------------------------------------
# Main metrics
# -------------------------------------------------------------------

metric_columns = st.columns(5)

metric_columns[0].metric(
    label="Participants",
    value=participant_total,
)

metric_columns[1].metric(
    label="Conditions",
    value=condition_total,
)

metric_columns[2].metric(
    label="Conversation Turns",
    value=conversation_turn_total,
)

metric_columns[3].metric(
    label="Overall Mean Trust",
    value=f"{mean_trust:.2f} / 5",
)

metric_columns[4].metric(
    label="Mean Risk Awareness",
    value=f"{mean_risk_awareness:.2f} / 5",
)


# -------------------------------------------------------------------
# Tabs
# -------------------------------------------------------------------

(
    overview_tab,
    group_tab,
    statistics_tab,
    experience_tab,
    conversation_tab,
    data_tab,
) = st.tabs(
    [
        "Research Overview",
        "Disclosure Groups",
        "Statistical Analysis",
        "Experience Levels",
        "Conversation Analysis",
        "Data Tables",
    ]
)


# -------------------------------------------------------------------
# Research overview
# -------------------------------------------------------------------

with overview_tab:
    st.subheader("Disclosure-Condition Overview")

    overview_columns = st.columns(2)

    with overview_columns[0]:
        trust_figure = px.bar(
            group_summary,
            x="experiment_condition",
            y="mean_trust",
            title=(
                "Mean Trust Score by Disclosure Condition"
            ),
        )

        trust_figure.update_traces(
            texttemplate="%{y:.2f}",
            textposition="outside",
        )

        trust_figure.update_layout(
            xaxis_title="Disclosure Condition",
            yaxis_title="Mean Trust Score",
        )

        trust_figure.update_yaxes(
            range=[1, 5]
        )

        st.plotly_chart(
            trust_figure,
            use_container_width=True,
        )

    with overview_columns[1]:
        risk_awareness_figure = px.bar(
            group_summary,
            x="experiment_condition",
            y="mean_risk_awareness",
            title=(
                "Mean Risk-Awareness Score by Condition"
            ),
        )

        risk_awareness_figure.update_traces(
            texttemplate="%{y:.2f}",
            textposition="outside",
        )

        risk_awareness_figure.update_layout(
            xaxis_title="Disclosure Condition",
            yaxis_title="Mean Risk-Awareness Score",
        )

        risk_awareness_figure.update_yaxes(
            range=[1, 5]
        )

        st.plotly_chart(
            risk_awareness_figure,
            use_container_width=True,
        )

    st.subheader("AI Identity Recognition")

    ai_identity_figure = px.bar(
        group_summary,
        x="experiment_condition",
        y="ai_identification_rate",
        title=(
            "Participants Identifying the System as AI"
        ),
    )

    ai_identity_figure.update_traces(
        texttemplate="%{y:.1%}",
        textposition="outside",
    )

    ai_identity_figure.update_layout(
        xaxis_title="Disclosure Condition",
        yaxis_title="Identification Rate",
    )

    ai_identity_figure.update_yaxes(
        tickformat=".0%",
        range=[0, 1],
    )

    st.plotly_chart(
        ai_identity_figure,
        use_container_width=True,
    )

    st.info(
        "Differences shown in synthetic mode are deliberately "
        "generated for software testing and have no empirical meaning."
    )


# -------------------------------------------------------------------
# Disclosure groups
# -------------------------------------------------------------------

with group_tab:
    st.subheader("Group-Level Comparison")

    display_group_summary = group_summary.copy()

    display_group_summary[
        "ai_identification_rate"
    ] = display_group_summary[
        "ai_identification_rate"
    ].map(
        lambda value: f"{value:.1%}"
    )

    score_columns = [
        "mean_trust",
        "mean_risk_awareness",
        "mean_disclosure_clarity",
        "mean_helpfulness",
    ]

    for column in score_columns:
        display_group_summary[column] = (
            display_group_summary[column].map(
                lambda value: f"{value:.2f}"
            )
        )

    st.dataframe(
        display_group_summary,
        use_container_width=True,
        hide_index=True,
    )

    st.divider()

    metric_selection = st.selectbox(
        "Select a metric for distribution analysis",
        options=[
            "trust_score",
            "risk_awareness_score",
            "disclosure_clear",
            "overall_helpfulness",
        ],
    )

    metric_title = (
        metric_selection
        .replace("_", " ")
        .title()
    )

    distribution_figure = px.box(
        enriched_survey_data,
        x="experiment_condition",
        y=metric_selection,
        points="all",
        title=(
            f"{metric_title} Distribution by Condition"
        ),
    )

    distribution_figure.update_layout(
        xaxis_title="Disclosure Condition",
        yaxis_title=metric_title,
    )

    if metric_selection != "overall_helpfulness":
        distribution_figure.update_yaxes(
            range=[1, 5]
        )
    else:
        distribution_figure.update_yaxes(
            range=[0, 10]
        )

    st.plotly_chart(
        distribution_figure,
        use_container_width=True,
    )


# -------------------------------------------------------------------
# Experience analysis
# -------------------------------------------------------------------

with statistics_tab:
    st.subheader(
        "Scale Reliability and Group Statistics"
    )

    st.warning(
        "Statistical results generated from synthetic data are "
        "software demonstrations only and are not empirical findings."
    )

    trust_items = [
        "trust_reliable",
        "trust_confident",
        "credibility_clear",
    ]

    risk_awareness_items = [
        "risk_awareness",
        "risk_understanding",
    ]

    trust_alpha = calculate_cronbach_alpha(
        enriched_survey_data,
        trust_items,
    )

    risk_alpha = calculate_cronbach_alpha(
        enriched_survey_data,
        risk_awareness_items,
    )

    st.markdown("### Internal Consistency")

    reliability_columns = st.columns(2)

    reliability_columns[0].metric(
        label="Trust Scale Cronbach's Alpha",
        value=(
            f"{trust_alpha:.3f}"
            if trust_alpha is not None
            else "N/A"
        ),
    )

    reliability_columns[0].caption(
        classify_cronbach_alpha(
            trust_alpha
        )
    )

    reliability_columns[1].metric(
        label="Risk-Awareness Alpha",
        value=(
            f"{risk_alpha:.3f}"
            if risk_alpha is not None
            else "N/A"
        ),
    )

    reliability_columns[1].caption(
        classify_cronbach_alpha(
            risk_alpha
        )
    )

    st.caption(
        "Cronbach's alpha estimates whether items intended to "
        "measure the same construct produce internally consistent "
        "responses. A high alpha does not by itself prove validity."
    )

    st.divider()

    st.markdown(
        "### Confidence Intervals by Disclosure Condition"
    )

    statistical_metric = st.selectbox(
        "Select outcome variable",
        options=[
            "Trust score",
            "Risk-awareness score",
            "Disclosure clarity",
            "Overall helpfulness",
        ],
    )

    metric_mapping = {
        "Trust score": "trust_score",
        "Risk-awareness score": (
            "risk_awareness_score"
        ),
        "Disclosure clarity": (
            "disclosure_clear"
        ),
        "Overall helpfulness": (
            "overall_helpfulness"
        ),
    }

    selected_statistical_metric = (
        metric_mapping[
            statistical_metric
        ]
    )

    confidence_intervals = (
        calculate_group_confidence_intervals(
            data=enriched_survey_data,
            metric_column=(
                selected_statistical_metric
            ),
            confidence_level=0.95,
        )
    )

    formatted_confidence_intervals = (
        confidence_intervals.copy()
    )

    for column in [
        "mean",
        "standard_deviation",
        "standard_error",
        "lower_bound",
        "upper_bound",
    ]:
        formatted_confidence_intervals[
            column
        ] = formatted_confidence_intervals[
            column
        ].map(
            lambda value: (
                f"{value:.3f}"
                if pd.notna(value)
                else ""
            )
        )

    st.dataframe(
        formatted_confidence_intervals,
        use_container_width=True,
        hide_index=True,
    )

    confidence_figure = px.scatter(
        confidence_intervals,
        x="experiment_condition",
        y="mean",
        error_y=(
            confidence_intervals[
                "upper_bound"
            ]
            - confidence_intervals["mean"]
        ),
        error_y_minus=(
            confidence_intervals["mean"]
            - confidence_intervals[
                "lower_bound"
            ]
        ),
        title=(
            f"{statistical_metric}: "
            "Group Means with 95% Confidence Intervals"
        ),
    )

    confidence_figure.update_traces(
        marker={
            "size": 12,
        }
    )

    confidence_figure.update_layout(
        xaxis_title="Disclosure Condition",
        yaxis_title=statistical_metric,
    )

    if (
        selected_statistical_metric
        != "overall_helpfulness"
    ):
        confidence_figure.update_yaxes(
            range=[1, 5]
        )
    else:
        confidence_figure.update_yaxes(
            range=[0, 10]
        )

    st.plotly_chart(
        confidence_figure,
        use_container_width=True,
    )

    st.caption(
        "The confidence interval describes uncertainty around "
        "each estimated group mean. Overlapping intervals do not "
        "automatically prove that groups are equal."
    )

    st.divider()

    st.markdown("### One-Way ANOVA")

    anova_result = run_one_way_anova(
        data=enriched_survey_data,
        metric_column=(
            selected_statistical_metric
        ),
    )

    if not anova_result["valid"]:
        st.warning(
            anova_result["interpretation"]
        )

    else:
        anova_columns = st.columns(3)

        anova_columns[0].metric(
            label="F Statistic",
            value=(
                f"{anova_result['f_statistic']:.3f}"
            ),
        )

        anova_columns[1].metric(
            label="P Value",
            value=(
                f"{anova_result['p_value']:.4f}"
            ),
        )

        anova_columns[2].metric(
            label="Eta-Squared",
            value=(
                f"{anova_result['eta_squared']:.3f}"
                if anova_result[
                    "eta_squared"
                ] is not None
                else "N/A"
            ),
        )

        st.write(
            "**Effect-size classification:** "
            f"{anova_result['effect_classification']}"
        )

        if anova_result["p_value"] < 0.05:
            st.success(
                anova_result[
                    "interpretation"
                ]
            )
        else:
            st.info(
                anova_result[
                    "interpretation"
                ]
            )

        st.caption(
            "ANOVA assumes independent observations, approximately "
            "normally distributed residuals and reasonably similar "
            "group variances. A statistically significant result "
            "does not necessarily represent a practically important effect."
        )

    st.divider()

    st.markdown(
        "### Tukey HSD Pairwise Comparisons"
    )

    tukey_results = run_tukey_hsd(
        data=enriched_survey_data,
        metric_column=(
            selected_statistical_metric
        ),
    )

    if tukey_results.empty:
        st.info(
            "Pairwise comparisons could not be calculated. "
            "Each comparison requires sufficient valid observations."
        )

    else:
        formatted_tukey_results = (
            tukey_results.copy()
        )

        formatted_tukey_results[
            "mean_difference"
        ] = formatted_tukey_results[
            "mean_difference"
        ].map(
            lambda value: f"{value:.3f}"
        )

        formatted_tukey_results[
            "p_value"
        ] = formatted_tukey_results[
            "p_value"
        ].map(
            lambda value: (
                "< 0.001"
                if value < 0.001
                else f"{value:.3f}"
            )
        )

        for column in [
            "confidence_low",
            "confidence_high",
        ]:
            formatted_tukey_results[
                column
            ] = formatted_tukey_results[
                column
            ].map(
                lambda value: f"{value:.3f}"
            )

        formatted_tukey_results[
            "significant"
        ] = formatted_tukey_results[
            "significant"
        ].map(
            {
                True: "Yes",
                False: "No",
            }
        )

        st.dataframe(
            formatted_tukey_results,
            use_container_width=True,
            hide_index=True,
        )

        significant_comparisons = (
            tukey_results[
                tukey_results["significant"]
            ]
        )

        if significant_comparisons.empty:
            st.info(
                "No pairwise comparison was statistically "
                "significant after Tukey's multiple-comparison adjustment."
            )

        else:
            st.success(
                f"{len(significant_comparisons)} statistically "
                "significant pairwise comparison(s) were identified."
            )

            for _, result_row in (
                significant_comparisons.iterrows()
            ):
                direction = (
                    "higher"
                    if result_row[
                        "mean_difference"
                    ] > 0
                    else "lower"
                )

                st.write(
                    f"- **{result_row['group_1']}** was "
                    f"{direction} than "
                    f"**{result_row['group_2']}** "
                    f"by approximately "
                    f"{abs(result_row['mean_difference']):.2f} "
                    f"points."
                )

        st.caption(
            "Tukey HSD compares all pairs of group means while "
            "controlling the overall family-wise error rate. "
            "The direction of the mean difference is calculated "
            "as group 1 minus group 2."
        )

    st.divider()

    st.markdown(
        "### Export Statistical Results"
    )

    statistical_report = (
        generate_statistical_report(
            survey_data=enriched_survey_data,
            metric_column=(
                selected_statistical_metric
            ),
            synthetic_data=(
                using_synthetic_data
            ),
        )
    )

    export_columns = st.columns(3)

    export_columns[0].download_button(
        label="Download Markdown report",
        data=statistical_report,
        file_name=(
            f"{selected_statistical_metric}"
            "_statistical_report.md"
        ),
        mime="text/markdown",
        use_container_width=True,
    )

    export_columns[1].download_button(
        label="Download confidence intervals",
        data=(
            confidence_intervals
            .to_csv(index=False)
            .encode("utf-8")
        ),
        file_name=(
            f"{selected_statistical_metric}"
            "_confidence_intervals.csv"
        ),
        mime="text/csv",
        use_container_width=True,
    )

    export_columns[2].download_button(
        label="Download Tukey results",
        data=(
            tukey_results
            .to_csv(index=False)
            .encode("utf-8")
        ),
        file_name=(
            f"{selected_statistical_metric}"
            "_tukey_hsd.csv"
        ),
        mime="text/csv",
        use_container_width=True,
    )

    with st.expander(
        "Preview generated report"
    ):
        st.markdown(
            statistical_report
        )

with experience_tab:
    st.subheader("Results by Trading Experience")

    experience_summary = (
        calculate_experience_summary(
            enriched_survey_data
        )
    )

    formatted_experience_summary = (
        experience_summary.copy()
    )

    for column in [
        "mean_trust",
        "mean_risk_awareness",
        "mean_helpfulness",
    ]:
        formatted_experience_summary[
            column
        ] = formatted_experience_summary[
            column
        ].map(
            lambda value: f"{value:.2f}"
        )

    st.dataframe(
        formatted_experience_summary,
        use_container_width=True,
        hide_index=True,
    )

    experience_long = experience_summary.melt(
        id_vars=[
            "experience_level",
            "participants",
        ],
        value_vars=[
            "mean_trust",
            "mean_risk_awareness",
        ],
        var_name="metric",
        value_name="mean_score",
    )

    experience_figure = px.bar(
        experience_long,
        x="experience_level",
        y="mean_score",
        color="metric",
        barmode="group",
        title=(
            "Trust and Risk Awareness by Experience Level"
        ),
    )

    experience_figure.update_layout(
        xaxis_title="Experience Level",
        yaxis_title="Mean Score",
        legend_title="Metric",
    )

    experience_figure.update_yaxes(
        range=[1, 5]
    )

    st.plotly_chart(
        experience_figure,
        use_container_width=True,
    )


# -------------------------------------------------------------------
# Conversation analysis
# -------------------------------------------------------------------

with conversation_tab:
    st.subheader("Conversation Behaviour")

    if conversation_data.empty:
        st.info(
            "No conversation-level dataset was provided."
        )

    else:
        intent_summary = calculate_intent_summary(
            conversation_data
        )

        risk_summary = calculate_risk_summary(
            conversation_data
        )

        conversation_columns = st.columns(2)

        with conversation_columns[0]:
            intent_figure = px.bar(
                intent_summary,
                x="conversation_turns",
                y="detected_intent",
                orientation="h",
                title="Detected Intent Frequency",
            )

            intent_figure.update_layout(
                xaxis_title="Conversation Turns",
                yaxis_title="Intent",
            )

            st.plotly_chart(
                intent_figure,
                use_container_width=True,
            )

        with conversation_columns[1]:
            risk_figure = px.pie(
                risk_summary,
                names="risk_level",
                values="conversation_turns",
                title="Conversation Risk Levels",
                hole=0.45,
            )

            st.plotly_chart(
                risk_figure,
                use_container_width=True,
            )

        st.subheader("Response-Time Distribution")

        response_time_figure = px.histogram(
            conversation_data,
            x="response_time_ms",
            nbins=30,
            title=(
                "Rule-Based Response Generation Time"
            ),
        )

        response_time_figure.update_layout(
            xaxis_title="Response Time (ms)",
            yaxis_title="Conversation Turns",
        )

        st.plotly_chart(
            response_time_figure,
            use_container_width=True,
        )

        average_response_time = conversation_data[
            "response_time_ms"
        ].mean()

        maximum_response_time = conversation_data[
            "response_time_ms"
        ].max()

        response_metric_columns = st.columns(2)

        response_metric_columns[0].metric(
            label="Average Response Time",
            value=f"{average_response_time:.2f} ms",
        )

        response_metric_columns[1].metric(
            label="Maximum Response Time",
            value=f"{maximum_response_time:.2f} ms",
        )


# -------------------------------------------------------------------
# Data tables and exports
# -------------------------------------------------------------------

with data_tab:
    st.subheader("Survey Data")

    st.dataframe(
        enriched_survey_data,
        use_container_width=True,
        hide_index=True,
    )

    st.download_button(
        label="Download enriched survey data",
        data=(
            enriched_survey_data
            .to_csv(index=False)
            .encode("utf-8")
        ),
        file_name="research_survey_enriched.csv",
        mime="text/csv",
        use_container_width=True,
    )

    if not conversation_data.empty:
        st.divider()

        st.subheader("Conversation Data")

        st.dataframe(
            conversation_data,
            use_container_width=True,
            hide_index=True,
        )

        st.download_button(
            label="Download conversation analysis data",
            data=(
                conversation_data
                .to_csv(index=False)
                .encode("utf-8")
            ),
            file_name="research_conversation_data.csv",
            mime="text/csv",
            use_container_width=True,
        )


st.divider()

st.caption(
    "This dashboard is a portfolio and research-prototype tool. "
    "Synthetic data must not be interpreted as real study findings."
)